# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ReactNativeWeb' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for ReactNativeWeb
  pod 'AppCenterReactNativeShared', '~> 1.4.0'

  

  platform :ios, '9.0'
  target 'ReactNativeWebTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'ReactNativeWeb-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for ReactNativeWeb-tvOS

  target 'ReactNativeWeb-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
